const KEY='couplebudget-v3',OLD2='couplebudget-v2',OLD1='couplebudget-v1';
let db=load();const $=s=>document.querySelector(s);const money=n=>db.currency+Number(n||0).toFixed(2);
function load(){let x=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(OLD2)||localStorage.getItem(OLD1)||'null');if(!x)x={transactions:[],recurring:[],budgets:{Groceries:600,Bills:400,Fun:200},rules:[],currency:'€'};x.transactions??=[];x.recurring??=[];x.budgets??={};x.rules??=[];x.currency??='€';return x}
function persist(){localStorage.setItem(KEY,JSON.stringify(db))}function save(){persist();render()}
function today(){return new Date().toISOString().slice(0,10)}function thisMonth(){return today().slice(0,7)}function parseDate(s){return new Date(s+'T12:00:00')}function iso(d){return d.toISOString().slice(0,10)}
function advance(date,cadence){const d=parseDate(date);if(cadence==='weekly')d.setDate(d.getDate()+7);else{const day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+1);const last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(day,last))}return iso(d)}
function applyRules(text,fallback='Uncategorized'){const s=String(text||'').toLowerCase();for(const r of db.rules){if(s.includes(String(r.contains||'').toLowerCase()))return r.category}return fallback}
function materializeRecurring(){let changed=false;for(const r of db.recurring){let guard=0;while(r.nextDate<=today()&&guard++<500){const exists=db.transactions.some(t=>t.recurrenceId===r.id&&t.occurrence===r.nextDate);if(!exists)db.transactions.push({id:crypto.randomUUID(),date:r.nextDate,type:r.type,amount:r.amount,category:r.category,member:r.member,note:r.note||'',recurrenceId:r.id,occurrence:r.nextDate});r.nextDate=advance(r.nextDate,r.cadence);changed=true}}if(changed)persist()}
function projectedRecurring(days){const end=new Date();end.setDate(end.getDate()+days);const endIso=iso(end),rows=[];for(const r of db.recurring){let d=r.nextDate,guard=0;while(d<=endIso&&guard++<500){rows.push({...r,date:d});d=advance(d,r.cadence)}}return rows}
function forecast(days){const start=today(),end=new Date();end.setDate(end.getDate()+days);const endIso=iso(end);let balance=db.transactions.filter(t=>t.date<=start).reduce((a,t)=>a+(t.type==='income'?t.amount:-t.amount),0);for(const t of db.transactions.filter(t=>t.date>start&&t.date<=endIso))balance+=t.type==='income'?t.amount:-t.amount;for(const r of projectedRecurring(days))balance+=r.type==='income'?r.amount:-r.amount;return balance}
function upcoming(days=30){return projectedRecurring(days).filter(r=>r.type==='expense').sort((a,b)=>a.date.localeCompare(b.date))}
function render(){const m=$('#viewMonth').value||thisMonth(),tx=db.transactions.filter(x=>x.date.startsWith(m));const inc=tx.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0),sp=tx.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0);$('#income').textContent=money(inc);$('#spent').textContent=money(sp);$('#left').textContent=money(inc-sp);const cats={};tx.filter(x=>x.type==='expense').forEach(x=>cats[x.category]=(cats[x.category]||0)+x.amount);$('#budgets').innerHTML=Object.entries(db.budgets).map(([c,b])=>{const u=cats[c]||0,p=Math.min(100,u/b*100||0);return `<div class=budget><div class=row><b>${esc(c)}</b><span>${money(u)} / ${money(b)}</span></div><div class=bar><i style="width:${p}%"></i></div></div>`}).join('')||'<p>No category budgets.</p>';const byMember={};tx.forEach(x=>{const k=x.member||'Household';byMember[k]??={income:0,expense:0};byMember[k][x.type]+=x.amount});$('#members').innerHTML=Object.entries(byMember).map(([n,v])=>`<div class=member><b>${esc(n)}</b><span>+${money(v.income)} / -${money(v.expense)}</span></div>`).join('')||'<p>No activity this month.</p>';const q=$('#search').value.toLowerCase();$('#tx').innerHTML=[...tx].sort((a,b)=>b.date.localeCompare(a.date)).filter(x=>JSON.stringify(x).toLowerCase().includes(q)).map(x=>`<div class=tx><span>${x.date}</span><span>${x.type}</span><span>${esc(x.category)}</span><span class=hide-sm>${esc(x.member)} ${esc(x.note||'')}</span><span class=amount>${x.type==='expense'?'-':'+'}${money(x.amount)}</span><button onclick="delTx('${x.id}')">×</button></div>`).join('')||'<p>No transactions for this month.</p>';$('#recurring').innerHTML=db.recurring.map(r=>`<div class=recrow><span>${r.nextDate}</span><span>${r.cadence}</span><span>${esc(r.category)}</span><span class=hide-sm>${esc(r.member)} ${esc(r.note||'')}</span><span class=amount>${r.type==='expense'?'-':'+'}${money(r.amount)}</span><button onclick="delRec('${r.id}')">×</button></div>`).join('')||'<p>No recurring transactions.</p>';const bills=upcoming(30);$('#upcoming').innerHTML=bills.slice(0,20).map(r=>`<div class=recrow><span>${r.date}</span><span>${esc(r.category)}</span><span class=hide-sm>${esc(r.note||r.member)}</span><span class=amount>-${money(r.amount)}</span></div>`).join('')||'<p>No expenses due in the next 30 days.</p>';$('#forecast').innerHTML=[30,60,90].map(d=>`<article><span>${d} days</span><b>${money(forecast(d))}</b></article>`).join('');$('#rules').innerHTML=db.rules.map((r,i)=>`<div class=recrow><span>contains “${esc(r.contains)}”</span><span>→ ${esc(r.category)}</span><button onclick="delRule(${i})">×</button></div>`).join('')||'<p>No auto-category rules.</p>'}
$('#viewMonth').value=thisMonth();$('#form').date.value=today();$('#recForm').start.value=today();
$('#form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),note=f.get('note').trim(),raw=f.get('category').trim();db.transactions.push({id:crypto.randomUUID(),date:f.get('date'),type:f.get('type'),amount:Number(f.get('amount')),category:raw||applyRules(note),member:f.get('member').trim()||'Household',note});e.target.amount.value='';e.target.note.value='';save()};
$('#recForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),start=f.get('start'),note=f.get('note').trim(),raw=f.get('category').trim();db.recurring.push({id:crypto.randomUUID(),start,nextDate:start,cadence:f.get('cadence'),type:f.get('type'),amount:Number(f.get('amount')),category:raw||applyRules(note),member:f.get('member').trim()||'Household',note});materializeRecurring();e.target.amount.value='';e.target.note.value='';save()};
window.delTx=id=>{db.transactions=db.transactions.filter(x=>x.id!==id);save()};window.delRec=id=>{if(confirm('Delete this recurring schedule? Existing generated transactions stay in history.')){db.recurring=db.recurring.filter(x=>x.id!==id);save()}};window.delRule=i=>{db.rules.splice(i,1);save()};
$('#search').oninput=render;$('#viewMonth').oninput=render;$('#addBudget').onclick=()=>{const c=prompt('Category name');if(!c)return;const a=Number(prompt('Monthly budget amount'));if(a>0){db.budgets[c]=a;save()}};$('#addRule').onclick=()=>{const contains=prompt('If description contains…');if(!contains)return;const category=prompt('Set category to…');if(category){db.rules.push({contains,category});save()}};
$('#exportJson').onclick=()=>download('couplebudget-backup.json',JSON.stringify(db,null,2),'application/json');$('#exportCsv').onclick=()=>{const lines=[['date','type','amount','category','member','note'],...db.transactions.map(x=>[x.date,x.type,x.amount,x.category,x.member,x.note])].map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');download('couplebudget.csv',lines,'text/csv')};
$('#importJson').onchange=async e=>{try{const x=JSON.parse(await e.target.files[0].text());if(Array.isArray(x.transactions)&&x.budgets){db=x;db.recurring??=[];db.rules??=[];persist();materializeRecurring();render()}}catch{alert('Invalid backup')}};
function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}
function importCsv(text){const rows=parseCsv(text);if(rows.length<2)return 0;const h=rows[0].map(x=>x.trim().toLowerCase()),idx=n=>h.indexOf(n);let count=0;for(const r of rows.slice(1)){const date=r[idx('date')]||'',desc=r[idx('description')]||r[idx('note')]||r[idx('payee')]||'',raw=Number(String(r[idx('amount')]||'0').replace(/[^0-9+-.]/g,''));if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(raw)||raw===0)continue;const explicit=(r[idx('type')]||'').toLowerCase(),type=explicit==='income'||explicit==='expense'?explicit:(raw<0?'expense':'income'),category=(r[idx('category')]||'').trim()||applyRules(desc);db.transactions.push({id:crypto.randomUUID(),date,type,amount:Math.abs(raw),category,member:(r[idx('member')]||'Household').trim()||'Household',note:desc.trim(),imported:true});count++}persist();render();return count}
$('#importCsv').onchange=async e=>{try{const n=importCsv(await e.target.files[0].text());alert(`Imported ${n} transactions.`)}catch{alert('Could not import CSV')}};
function download(n,s,t){const u=URL.createObjectURL(new Blob([s],{type:t})),a=document.createElement('a');a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}function esc(s){return String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
materializeRecurring();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
